### ISSUE TITLE
Tweak mutations example on the demo page

### ISSUE THREAD

**Issue by johnotander** [johnotander/immutable-css#22]
When changing a framework without modifying the custom CSS, the majority of the frameworks don't raise any mutation errors. Changing the CSS to something like the following would ensure that error examples are reported for all available frameworks:

```css
/* These are examples of mutations */
.red, .btn-warning, .button, .pure-button, .Button, .b--red {
  color: orangered;
}
.btn, .button, .pure-button, .Button, .mw--100 {
  width: 100%;
}
```
